"""add_last_name_and_language_code_to_users

Revision ID: 3feb40520652
Revises: c4eb163f0920
Create Date: 2025-10-16 16:45:52.722047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feb40520652'
down_revision: Union[str, Sequence[str], None] = 'c4eb163f0920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
